apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: mern-app
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: bW9uZ29hZG1pbg==   # mongoadmin
  MONGO_INITDB_ROOT_PASSWORD: bW9uZ29wYXNz       # mongopass